//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icom_Proxy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public string BaudComboBox {
            get {
                return ((string)(this["BaudComboBox"]));
            }
            set {
                this["BaudComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM0")]
        public string ComPortNumber1 {
            get {
                return ((string)(this["ComPortNumber1"]));
            }
            set {
                this["ComPortNumber1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM0")]
        public string ComPortNumber2 {
            get {
                return ((string)(this["ComPortNumber2"]));
            }
            set {
                this["ComPortNumber2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM0")]
        public string ComPortNumber3 {
            get {
                return ((string)(this["ComPortNumber3"]));
            }
            set {
                this["ComPortNumber3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM0")]
        public string ComPortNumber4 {
            get {
                return ((string)(this["ComPortNumber4"]));
            }
            set {
                this["ComPortNumber4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_PTT_RTS {
            get {
                return ((bool)(this["checkBox_PTT_RTS"]));
            }
            set {
                this["checkBox_PTT_RTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_PTT_CIV {
            get {
                return ((bool)(this["checkBox_PTT_CIV"]));
            }
            set {
                this["checkBox_PTT_CIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_FeedBack2 {
            get {
                return ((bool)(this["checkBox_FeedBack2"]));
            }
            set {
                this["checkBox_FeedBack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_FeedBack3 {
            get {
                return ((bool)(this["checkBox_FeedBack3"]));
            }
            set {
                this["checkBox_FeedBack3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_FeedBack4 {
            get {
                return ((bool)(this["checkBox_FeedBack4"]));
            }
            set {
                this["checkBox_FeedBack4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxForceCIV {
            get {
                return ((bool)(this["checkBoxForceCIV"]));
            }
            set {
                this["checkBoxForceCIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program 1")]
        public string port_name2 {
            get {
                return ((string)(this["port_name2"]));
            }
            set {
                this["port_name2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program 2")]
        public string port_name3 {
            get {
                return ((string)(this["port_name3"]));
            }
            set {
                this["port_name3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program 3")]
        public string port_name4 {
            get {
                return ((string)(this["port_name4"]));
            }
            set {
                this["port_name4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Ptt_timeout {
            get {
                return ((int)(this["Ptt_timeout"]));
            }
            set {
                this["Ptt_timeout"] = value;
            }
        }
    }
}
