//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icom_Proxy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public string BaudComboBox {
            get {
                return ((string)(this["BaudComboBox"]));
            }
            set {
                this["BaudComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM0")]
        public string ComPortNumberRadio {
            get {
                return ((string)(this["ComPortNumberRadio"]));
            }
            set {
                this["ComPortNumberRadio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com0com")]
        public string ComPortNumberProgram1 {
            get {
                return ((string)(this["ComPortNumberProgram1"]));
            }
            set {
                this["ComPortNumberProgram1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com0com")]
        public string ComPortNumberProgram2 {
            get {
                return ((string)(this["ComPortNumberProgram2"]));
            }
            set {
                this["ComPortNumberProgram2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com0com")]
        public string ComPortNumberProgram3 {
            get {
                return ((string)(this["ComPortNumberProgram3"]));
            }
            set {
                this["ComPortNumberProgram3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_PTT_RTS {
            get {
                return ((bool)(this["checkBox_PTT_RTS"]));
            }
            set {
                this["checkBox_PTT_RTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_PTT_CIV {
            get {
                return ((bool)(this["checkBox_PTT_CIV"]));
            }
            set {
                this["checkBox_PTT_CIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_FeedBackProgram1 {
            get {
                return ((bool)(this["checkBox_FeedBackProgram1"]));
            }
            set {
                this["checkBox_FeedBackProgram1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_FeedBackProgram2 {
            get {
                return ((bool)(this["checkBox_FeedBackProgram2"]));
            }
            set {
                this["checkBox_FeedBackProgram2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBox_FeedBackProgram3 {
            get {
                return ((bool)(this["checkBox_FeedBackProgram3"]));
            }
            set {
                this["checkBox_FeedBackProgram3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxForceCIV {
            get {
                return ((bool)(this["checkBoxForceCIV"]));
            }
            set {
                this["checkBoxForceCIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program 1")]
        public string port_nameProgram1 {
            get {
                return ((string)(this["port_nameProgram1"]));
            }
            set {
                this["port_nameProgram1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program 2")]
        public string port_nameProgram2 {
            get {
                return ((string)(this["port_nameProgram2"]));
            }
            set {
                this["port_nameProgram2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Program 3")]
        public string port_nameProgram3 {
            get {
                return ((string)(this["port_nameProgram3"]));
            }
            set {
                this["port_nameProgram3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Ptt_timeout {
            get {
                return ((int)(this["Ptt_timeout"]));
            }
            set {
                this["Ptt_timeout"] = value;
            }
        }
    }
}
